name: Codecov workflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Lint
      run: |
        flake8 . --max-complexity=12 --max-line-length=88 --select=C,E,F,W,B,B950,BLK --ignore=E203,E231,E501,W503
    - name: Generate coverage report
      run: |
        python -m pytest --cov continual --cov-report=xml -m "not skip_cicd"
    - name: Upload coverage to Codecov  
      run: |
        bash <(curl -s https://codecov.io/bash) -c -F unittests -t ${{ secrets.CODECOV_TOKEN }}

